# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Class
version:      0.03
version_from: lib/WebService/Class.pm
installdirs:  site
requires:
    Cache::Memcached::Fast:        0
    CGI:                           0
    Class::Accessor:               0
    Class::Data::Inheritable:      0
    Digest::MD5:                   0
    JSON:                          0
    LWP:                           0
    Test::More:                    0
    XML::Simple:                   0
    XMLRPC::Lite:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
